Update download.yml

diff --git a/.github/workflows/download.yml b/.github/workflows/download.yml
--- a/.github/workflows/download.yml
+++ b/.github/workflows/download.yml
@@ -23,13 +23,25 @@ jobs:
           sudo apt-get install -y ffmpeg
 
       - name: Download TikTok
-        run: |
-          mkdir -p output
-          yt-dlp \
-            --no-playlist \
-            --retries 3 \
-            -o "output/video.%(ext)s" \
-            "${{ inputs.url }}"
+       run: |
+           mkdir -p output
+
+           if ! yt-dlp \
+             --no-playlist \
+             --retries 3 \
+             -o "output/video.%(ext)s" \
+             "${{ inputs.url }}" 2>&1 | tee download.log; then
+
+             if grep -qi "Log in for access" download.log; then
+             echo "RESULT=LOGIN_REQUIRED" >> "$GITHUB_OUTPUT"
+             exit 0
+             fi
+
+             exit 1
+           fi
+
+           echo "RESULT=SUCCESS" >> "$GITHUB_OUTPUT"
+
 
       - name: Show downloaded file
         run: |
